# Generated by Django 2.1.7 on 2019-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_essay'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('essay', models.ForeignKey(on_delete='DESC', to='blog.Essay')),
            ],
        ),
    ]
