# Generated by Django 2.1.8 on 2019-04-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190406_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='main_img',
            field=models.ImageField(default=None, null=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(default=None, null=None, upload_to=''),
        ),
    ]
