# Generated by Django 2.1.8 on 2019-04-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190406_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='main_img',
        ),
    ]
