# Generated by Django 2.1.8 on 2019-04-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_essay_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='main_img',
            field=models.ImageField(default=None, null=None, upload_to=''),
        ),
    ]
