# Generated by Django 2.1.8 on 2019-04-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_essay_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='main_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='main_img',
            new_name='img',
        ),
    ]
