# Generated by Django 2.1.8 on 2019-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190406_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='img',
            field=models.ImageField(default=None, null=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, null=None, upload_to=''),
        ),
    ]
