# Generated by Django 2.1.8 on 2019-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190408_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=None, max_length=10000, null=None, upload_to='photo'),
        ),
    ]
